### ISSUE TITLE
Doesn't work...

### ISSUE THREAD

**Issue by Ashwanik936** [Snikkertjuh/Discord-Generator-Bot#15]
Traceback (most recent call last):
  File "c:\Users\Me\Desktop\GEN\Discord-Generator-Bot\LinkGen.py", line 16, in <module>
    client = discord.Bot()
AttributeError: module 'discord' has no attribute 'Bot'

**Comment by Crysiz2631** [comment]
me2

**Comment by Jeff53978** [comment]
Try uninstalling discord.py with:
pip uninstall discord.py
Then install py-cord with
pip install py-cord

**Comment by Crysiz2631** [comment]
still don't work

**Comment by Jeff53978** [comment]
I will fix this soon

**Comment by Crysiz2631** [comment]
thank you. im in desprate need of a gen bot

**Comment by Jeff53978** [comment]
Do you have any errors with the commands i mentioned above?

**Comment by Crysiz2631** [comment]
same error

**Comment by Crysiz2631** [comment]
Traceback (most recent call last):
  File "C:\Users\gronb\Desktop\heck\LinkGen-main\LinkGen.py", line 16, in <module>
    client = discord.Bot()
AttributeError: module 'discord' has no attribute 'Bot'

**Comment by Jeff53978** [comment]
Try running this command in your command prompt / terminal:

pip uninstall discord.py
pip install py-cord==2.0.0rc1
