### ISSUE TITLE
errors

### ISSUE THREAD

**Issue by unioninferno** [Snikkertjuh/Discord-Generator-Bot#20]
throws this error when i run python linkgen.py
the bot gets online but the slash commands dont show up
![image](https://user-images.githubusercontent.com/92788790/207152802-ca8a8ba8-e073-455b-9afe-fcd242bf3430.png)

**Comment by unioninferno** [comment]
also please let me know your new discord

**Comment by Jeff53978** [comment]
My new discord is: jeff$#4499, contact me here
