### ISSUE TITLE
Help pls

### ISSUE THREAD

**Issue by ImSpoofing** [Snikkertjuh/Discord-Generator-Bot#3]
When i say ?gen-netflix
The console say

[Error: ENOENT: no such file or directory, open './accounts/netflix.txt'] {
errno: -2,
code: 'ENCENT',
syscall: 'open',
path: './accounts/netflix.txt'
}

**Comment by SnikkerCC** [comment]
> When i say ?gen-netflix
> The console say
> 
> [Error: ENOENT: no such file or directory, open './accounts/netflix.txt'] {
> errno: -2,
> code: 'ENCENT',
> syscall: 'open',
> path: './accounts/netflix.txt'
> }

You need to put the content in the folder accounts with the name “netflix.txt”

**Comment by Shkeffy** [comment]
> > When i say ?gen-netflix
> > The console say
> > [Error: ENOENT: no such file or directory, open './accounts/netflix.txt'] {
> > errno: -2,
> > code: 'ENCENT',
> > syscall: 'open',
> > path: './accounts/netflix.txt'
> > }
> 
> You need to put the content in the folder accounts with the name “netflix.txt”

Where can I make or find netflix accounts?
