### ISSUE TITLE
Help!

### ISSUE THREAD

**Issue by Wuukong** [Snikkertjuh/Discord-Generator-Bot#6]
When generating an account and someone has disabled the ability to send private messages, I get an error: Unhandled promise rejection: DiscordAPIError: Cannot send messages to this user and the bot crashes.

**Comment by SnikkerCC** [comment]
In the next version i will fix this, somewhere next year

**Comment by Ripcord227** [comment]
> 

not trying to hurry you or anything but have you done this yet?
