### ISSUE TITLE
AttributeError: module 'discord' has no attribute 'Bot'

### ISSUE THREAD

**Issue by SenTheDev** [Snikkertjuh/Discord-Generator-Bot#8]
Traceback (most recent call last):
  File "C:\Users\AmongUs\Desktop\linkgen\linkgen.py", line 16, in <module>
    client = discord.Bot()
AttributeError: module 'discord' has no attribute 'Bot'

**Comment by strxangerfr** [comment]
got the same

**Comment by skyline69** [comment]
# **Possible fix** for @SenTheDev  
 

1. ### **Make sure you have the right `Pycord` library installed.**
2. ### **Try this command if you are on Windows: ``python -m pip install -U py-cord``**
3. ### **Run the program again**

**Comment by exoftondiscord** [comment]
you need to make client= discord.Client()

**Comment by Jeff53978** [comment]
Try deleteting discord.py with

```pip uninstall discord.py```
Then download py-cord with:
```pip install py-cord==2.0.0rc1```
